import 'package:flutter/cupertino.dart';

class Content{
  int point = 0;
  String start_line;
  String indexs;
  String indexe;
  String end_line;
  String start;
  String end;
  String slot;
  List slots = [
    '0900',
    '0905',
    '0910',
    '0915',
    '0920',
    '0925',
    '0930',
    '0935',
    '0940',
    '0945',
    '0950',
    '0955',
    '1000',
    '1005',
    '1010',
    '1015',
    '1020',
    '1025',
    '1030',
    '1035',
    '1040',
    '1045',
    '1050',
    '1055',
  ];
  List<String> listAllStations=[
    'Huda City Centre',
    'IIFCO Chowk',
    'M G Road',
    'Sikandarpur',
    'Guru Dhronacharya',
    'ArjanGarh',
    'Ghitorni',
    'Sultanpur',
    'Chhatarpur',
    'Qutub Minar',
    'Saket',
    'Malviya Nagar',
    'Hauz Khas',
    'Green Park',
    'AIIMS',
    'INA',
    'Jorbagh',
    'Lok Kalyan Marg',
    'Udyog Bhavan',
    'Central Secretariat',
    'Patel Chowk',
    'Rajiv Chowk',
    'New Delhi',
    'Chawri Bazar',
    'Chandni Chowk',
    'Kashmere Gate',


    'Noida Electronic City',
    'Sec-62',
    'Sec-59',
    'Sec-61',
    'Sec-52',
    'Sec-34',
    'Noida City Centre',
    'Golf Course',
    'Botanical Garden',
    'Sec 18',
    'Sec 16',
    'Sec 15',
    'New Ashok Nagar',
    'Mayur Vihar-1 EXT',
    'Mayur Vihar-1',
    'Akshardham',
    'Yamuna Bank',
    'Indraprastha',
    'Supreme Court',
    'Mandi House',
    'Barakhamba',
    'R.K.Ashram Marg',
    'Jhandewala',
    'Karol Bagh',
    'Rajendra Place',
    
    'Okhla Bird Sanctuary',
    'Kalindi Kunj',
    'J.V.Shaheen Bagh',
    'Okhla Vihar',
    'JM Islamia',
    'Sukhdev Vihar',
    'NSIC Okhla',
    'Kalkaji Mandir',
    'Nehru Enclave',
    'Greater Kailash',
    'Chirag Delhi',
    'Panchsheel Park',
    'I.I.T',
    'R.K.Puram',
    'Munirka',
    'Vasant Vihar',
    'Shankar Vihar',
    'IGD Airport',
    'Sadar Bazaar',
    'Palam',
    'Dashrathpuri',
    'Dabri Mor',
    'Janak Puri West',
  ];
  Map<String,dynamic> mapAllStations = {
    'Huda City Centre':"y01",
    'IIFCO Chowk':"y02",
    'M G Road':"y03",
    'Sikandarpur':"y04",
    'Guru Dhronacharya':"y05",
    'ArjanGarh':"y06",
    'Ghitorni':"y07",
    'Sultanpur':"y08",
    'Chhatarpur':"y09",
    'Qutub Minar':"y10",
    'Saket':"y11",
    'Malviya Nagar':"y12",
    'Hauz Khas':["y13","m14"],
    'Green Park':"y14",
    'AIIMS':"y15",
    'INA':"y16",
    'Jorbagh':"y17",
    'Lok Kalyan Marg':"y18",
    'Udyog Bhavan':"y19",
    'Central Secretariat':"y20",
    'Patel Chowk':"y21",
    'Rajiv Chowk':["y22","b22"],
    'New Delhi':"y23",
    'Chawri Bazar':"y24",
    'Chandni Chowk':"y25",
    'Kashmere Gate':"y26",


    'Noida Electronic City':"b01",
    'Sec-62':"b02",
    'Sec-59':"b03",
    'Sec-61':"b04",
    'Sec-52':"b05",
    'Sec-34':"b06",
    'Noida City Centre':"b07",
    'Golf Course':"b08",
    'Botanical Garden':["b09","m01"],
    'Sec 18':"b10",
    'Sec 16':"b11",
    'Sec 15':"b12",
    'New Ashok Nagar':"b13",
    'Mayur Vihar-1 EXT':"b14",
    'Mayur Vihar-1':"b15",
    'Akshardham':"b16",
    'Yamuna Bank':"b17",
    'Indraprastha':"b18",
    'Supreme Court':"b19",
    'Mandi House':"b20",
    'Barakhamba':"b21",
    'R.K.Ashram Marg':"b23",
    'Jhandewala':"b24",
    'Karol Bagh':"b25",
    'Rajendra Place':"b26",
    
    'Okhla Bird Sanctuary':"m02",
    'Kalindi Kunj':"m03",
    'J.V.Shaheen Bagh':"m04",
    'Okhla Vihar':"m05",
    'JM Islamia':"m06",
    'Sukhdev Vihar':"m07",
    'NSIC Okhla':"m08",
    'Kalkaji Mandir':"m09",
    'Nehru Enclave':"m10",
    'Greater Kailash':"m11",
    'Chirag Delhi':"m12",
    'Panchsheel Park':"m13",
    'I.I.T':"m15",
    'R.K.Puram':"m16",
    'Munirka':"m17",
    'Vasant Vihar':"m18",
    'Shankar Vihar':"m19",
    'IGD Airport':"m20",
    'Sadar Bazaar':"m21",
    'Palam':"m22",
    'Dashrathpuri':"m23",
    'Dabri Mor':"m24",
    'Janak Puri West':"m25",
  };
//   ];

//   Map<String,dynamic> mapAllStationsValues = {
//     'Huda City Centre':"y01",
//     'IIFCO Chowk':"y02",
//     'M G Road':"y03",
//     'Sikandarpur':"y04",
//     'Guru Dhronacharya':"y05",
//     'ArjanGarh':"y06",
//     'Ghitorni':"y07",
//     'Sultanpur':"y08",
//     'Chhatarpur':"y09",
//     'Qutub Minar':"y10",
//     'Saket':"y11",
//     'Malviya Nagar':"y12",
//     'Hauz Khas':["y13","m14"],
//     'Green Park':"y14",
//     'AIIMS':"y15",
//     'INA':"y16",
//     'Jorbagh':"y17",
//     'Lok Kalyan Marg':"y18",
//     'Udyog Bhavan':"y19",
//     'Central Secretariat':"y20",
//     'Patel Chowk':"y21",
//     'Rajiv Chowk':["y22","b22"],
//     'New Delhi':"y23",
//     'Chawri Bazar':"y24",
//     'Chandni Chowk':"y25",
//     'Kashmere Gate':"y26",


//     'Noida Electronic City':"b01",
//     'Sec-62':"b02",
//     'Sec-59':"b03",
//     'Sec-61':"b04",
//     'Sec-52':"b05",
//     'Sec-34':"b06",
//     'Noida City Centre':"b07",
//     'Golf Course':"b08",
//     'Botanical Garden':["b09","m01"],
//     'Sec 18':"b10",
//     'Sec 16':"b11",
//     'Sec 15':"b12",
//     'New Ashok Nagar':"b13",
//     'Mayur Vihar-1 EXT':"b14",
//     'Mayur Vihar-1':"b15",
//     'Akshardham':"b16",
//     'Yamuna Bank':"b17",
//     'Indraprastha':"b18",
//     'Supreme Court':"b19",
//     'Mandi House':"b20",
//     'Barakhamba':"b21",
//     'R.K.Ashram Marg':"b23",
//     'Jhandewala':"b24",
//     'Karol Bagh':"b25",
//     'Rajendra Place':"b26",
    
//     'Okhla Bird Sanctuary':"m02",
//     'Kalindi Kunj':"m03",
//     'J.V.Shaheen Bagh':"m04",
//     'Okhla Vihar':"m05",
//     'JM Islamia':"m06",
//     'Sukhdev Vihar':"m07",
//     'NSIC Okhla':"m08",
//     'Kalkaji Mandir':"m09",
//     'Nehru Enclave':"m10",
//     'Greater Kailash':"m11",
//     'Chirag Delhi':"m12",
//     'Panchsheel Park':"m13",
//     'I.I.T':"m15",
//     'R.K.Puram':"m16",
//     'Munirka':"m17",
//     'Vasant Vihar':"m18",
//     'Shankar Vihar':"m19",
//     'IGD Airport':"m20",
//     'Sadar Bazaar':"m21",
//     'Palam':"m22",
//     'Dashrathpuri':"m23",
//     'Dabri Mor':"m24",
//     'Janak Puri West':"m25",
//   };
}